### ISSUE TITLE
Serial hardware?

### ISSUE THREAD

**Issue by tnn2** [jonaz/gombus#1]
Hi,
Sorry not an issue per se, more of a support question.
I'd like to use this library with Carlo Gavazzi EM340 meters and a RPi4.
Do you have any recommendation for off-the-shelf hardware to provide serial port level shift and active power?

**Comment by jonaz** [comment]
@tnn2 i've successfully used both of those in different projects from rpi4 and this library:
* https://www.electrokit.com/en/m-bus-hat-for-raspberry-pi
* elvaco CMe3000
