### ISSUE TITLE
Unable to build on MacOS

### ISSUE THREAD

**Issue by ichnograph** [jonaz/gombus#2]
The underlying jonas/serial library's POSIX implementation lacks the `SetReadDeadline(t time.Time) (err error)` function.
This function is needed in Gombus to satisfy the `gombus.Conn` interface, which relies on it, so on Macos the build fails.

**Comment by jonaz** [comment]
The whole point of my fork is to implement just that and i know it works on Linux. If it doest work on Mac it's not because lack of interface implementation but due to the serial lib not supporting Mac. 

https://github.com/tarm/serial/compare/master...jonaz:serial:master

**Comment by ichnograph** [comment]
To be honest, I don't know if it "works" on Mac, as I have my serial code to read from M-bus. I only use your library to parse the messages, which works well on any platform. However, the hard failure to build it is not so great. All it takes is adding a function to `serial_posix.go`. I have forked Gombus and Serial to get it to work, which is a bit silly. Would you consider adding it so it builds on all POSIX systems that are not Linux? 

```go
func (p *Port) SetReadDeadline(t time.Time) (err error) {
	return p.f.SetReadDeadline(t) // Or return an error
}
```

**Comment by jonaz** [comment]
Ah now I get it. I only added to _linux.... Please make a PR to the other repo and I'll merge it and update this repo to use the new version.

**Comment by ichnograph** [comment]
I opened a PR for the changes to Serial. https://github.com/jonaz/serial/pull/1
After it is merged, I can open a PR for Gombus

**Comment by jonaz** [comment]
thanks @ichnograph! I've merged it now!

**Comment by ichnograph** [comment]
Awesome, I created a PR to bump the dependencies in Gombus: https://github.com/jonaz/gombus/pull/3

**Comment by jonaz** [comment]
@ichnograph thanks, merged it now!
